---
apiVersion: v1
kind: ConfigMap
data:
  colab.properties: |-
    colab.smtp.domain={{ .Values.colab.smtp.domain }}
    colab.smtp.auth={{ .Values.colab.smtp.auth }}
    colab.smtp.username={{ .Values.colab.smtp.username }}
    colab.smtp.password={{ .Values.colab.smtp.password }}
    colab.smtp.host={{ .Values.colab.smtp.host }}
    colab.smtp.port={{ .Values.colab.smtp.port }}
    colab.smtp.starttls={{ .Values.colab.smtp.starttls }} 
    {{ .Values.colab.extraproperties }}
metadata:
  name: {{ template "colab.fullname" . }}-user-config
  labels:
    app: {{ template "colab.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: v1
kind: ConfigMap
data:
  COLAB_DATABASE_NAME: {{ .Values.db.name }}
  COLAB_DATABASE_USER: {{ .Values.db.user }}
  COLAB_DEFAULT_ADMIN_USERNAME: {{ .Values.colab.admin.username }}
  COLAB_DEFAULT_ADMIN_EMAIL: {{ .Values.colab.admin.email }}
  HEAP_SIZE: {{ .Values.colab.java_heap }}M
  MIN_HTTP_THREADS: {{ .Values.colab.min_threads | quote }}
  MAX_HTTP_THREADS: {{ .Values.colab.max_threads | quote }}
metadata:
  name: {{ template "colab.fullname" . }}-hard-config
  labels:
    app: {{ template "colab.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: v1
data:
  COLAB_DEFAULT_ADMIN_PASSWORD: {{ .Values.colab.admin.password | b64enc }}
  COLAB_DATABASE_PASSWORD: {{ .Values.db.password | b64enc }}
kind: Secret
metadata:
  name: {{ template "colab.fullname" . }}-secret
  labels:
    app: {{ template "colab.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque

